name: blackcoffer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  chips_choice_null_safety: ^2.0.6
  cupertino_icons: ^1.0.6
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  velocity_x: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
   - lib/img/
